### ISSUE TITLE
Can't find variable: AlpineSelect

### ISSUE THREAD

**Issue by eddyinet** [presleyd/alpinejs-select#2]
This looks fantastic! While attempting to integrate it was getting errors about the data prop so I created a new Laravel component using

`php artisan make:component SelectSearch`

So that the SelectSearch.php component file is created:

`
namespace App\View\Components;

use Illuminate\View\Component;

class SelectSearch extends Component
{
    public $data;

    public function __construct($data)
    {
        $this->data = $data;
    }
   
    public function render()
    {
        return view('components.select-search');
    }
}
`

Once this was done I was able to render the component but now the console comes back with:

Can't find variable: AlpineSelect

I'm assuming I wasn't supposed to create the component that way... thoughts on what I missed?

Thanks!

**Comment by eddyinet** [comment]
OK I added: `@stack('body_scripts')` to my index blade. Renders now. 

Data isn't being populated just yet. In my livewire component I'm just initializing:

`public $data = [1 => "First Option", 2 => "Second Option"];` 

<x-select-search :data="$data" wire:model="email" placeholder="Select something!"/>

**Comment by eddyinet** [comment]
OK I added: `@stack('body_scripts')` to my index blade. Renders now. 

Data isn't being populated just yet. In my livewire component I'm just initializing:

`public $data = [1 => "First Option", 2 => "Second Option"];` 

<x-select-search :data="$data" wire:model="email" placeholder="Select something!"/>

**Comment by presleyd** [comment]
What's in the view for that component? If you added my file to say 'resource/views/components/select-search.blade.php' you should use it in your Livewire component like this:
<x-select-search :data=$data wire:model=??? />

If you don't wire:model here you won't be able to get the selected option back out. I do not render an html <select> list anywhere.

Ah yes, good point the body_scripts area was one of my own making. I'll update the documentation. Alternatively, I could just put it IN that component so you don't have to push it to a stack.

**Comment by eddyinet** [comment]
I just have this in my view:

`<x-select-search :data="$data" wire:model="email" placeholder="Select something" />`

I also noticed that the placeholder variable doesn't propagate over either. I know its on my end but I don't think any of the variables are getting passed over. I'm close though...

**Comment by eddyinet** [comment]
The livewire component:

```
namespace App\Http\Livewire;

use Livewire\Component;

class AddAppAdmin extends Component
{
    public $data;
    public $email;

    public function mount()
    {
        $this->data = [1 => "First Option", 2 => "Second Option"];
    }

    public function render()
    {
        return view('livewire.add-app-admin');
    }
}
```

**Comment by eddyinet** [comment]
Looks like the data is getting through:

<img width="967" alt="1" src="https://user-images.githubusercontent.com/8219203/110987026-7d654f80-833c-11eb-9ae0-fedb7cddcee7.png">

**Comment by presleyd** [comment]
Oh, do you have Alpine.JS on your page? This does depend on alpine.js
either added via NPM or by slapping

<script ***@***.***/dist/alpine.min.js"
defer></script>

in your layout

**Comment by eddyinet** [comment]
I do. I use it elsewhere as well so it's loaded:

```
<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
@stack('body_scripts')
```

**Comment by presleyd** [comment]
So there are no console errors but the select list is empty?

**Comment by eddyinet** [comment]
Exactly. I just updated to the latest Alpine no luck.

**Comment by eddyinet** [comment]
Heads up on your last commit to maybe inline the SVG's?

`Unable to locate a class or view for component [icon.x]`

**Comment by presleyd** [comment]
Fixed! I guess I need to keep my copy broken out if I'm going to share this
thing :)

**Comment by eddyinet** [comment]
Think I got it. 

Added following to app\View\Components\SelectSearch.php (created when using `php artisan make:component SelectSearch`)

Note I had to change `data` to `values` since data is a reserved keyword in blade components. Will follow-up with any tweaks but working well for now. Thanks for this and sticking with me :)

```
namespace App\View\Components;

use Illuminate\View\Component;

class SelectSearch extends Component
{
    public $values;
    public $limit;
    public $placeholder;
    
    public function __construct($values, $limit, $placeholder)
    {
        $this->values      = $values;
        $this->limit       = $limit;
        $this->placeholder = $placeholder;
    }
   
    public function render()
    {
        return view('components.select-search');
    }
}
```
