### ISSUE TITLE
HOWTO install

### ISSUE THREAD

**Issue by eugenevdm** [presleyd/alpinejs-select#4]
Hi,

I'm new to Alpine.

Where do I put the blade?

I tried running `php artisan livewire:make RandomComponent` and it seems the default locations for x-directives doesn't work.

The actual error I'm getting

`Unable to locate a class or view for component [select-search].`

Please help a noob.

**Comment by presleyd** [comment]
https://laravel.com/docs/8.x/blade#manually-registering-package-components

You can put it in either app/views/components or resources/views/components or manually register another location.
