### ISSUE TITLE
Does not work in Jetstream Modal

### ISSUE THREAD

**Issue by xjavun** [presleyd/alpinejs-select#5]
Thank you very much first of all for the very helpful tool.

Unfortunately, when I try to display it in a modal, it does not work. 

What could be the reason for that?

**Comment by presleyd** [comment]
Interesting, you'll have to tell me more I'm using it in jet stream models
here myself.

**Comment by xjavun** [comment]
Here is a sample code.

When I execute the code like this, I get the following view.
![modal](https://user-images.githubusercontent.com/78956891/112725716-ec849b80-8f19-11eb-8877-7015b6bf70b3.PNG)


modal-select.php
`<?php

namespace App\Http\Livewire;
use App\Models\Customer;


use Livewire\Component;

class ModalSelect extends Component
{
    public $customer_id;
    public $customers;

    public $modalCreate = false;

    public function createShowModal(){
        $this->reset();
        $this->modalCreate = true;
    }

    public function mount()
    {
        $this->customers = collect();
        $query=Customer::with('company')->orderBy('lastName')->get();
        foreach($query as $customer){
            $this->customers->put($customer->id, $customer->lastName . ', ' . $customer->firstName . ' - ' . $customer->company->name);
        }
        $this->customers = $this->customers->toArray();
    }

    public function render()
    {
        return view('livewire.modal-select');
    }
}
`

modal-select.blade.php
`<div>

<button type="button" wire:click="createShowModal" class="flex items-center px-5 py-2 mx-4 my-3 border border-gray-300 rounded-md text-gray-600 hover:bg-gray-600  hover:text-white text-sm font-medium focus:outline-none">
    <svg class="-ml-1 mr-2 h-5 w-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M11 9V5H9v4H5v2h4v4h2v-4h4V9h-4zm-1 11a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/></svg>
    Update
</button>


@if ($modalCreate)
<x-jet-dialog-modal wire:model="modalCreate">
    <x-slot name="title">
        {{ __('Update') }}
    </x-slot>

    <x-slot name="content">
            <div class="grid grid-cols-3 gap-4 pt-1.5">
                <div class="col-span-3">
                    <x-jet-label for="customer_id" value="{{ __('Kunde') }}" />
                    <x-select-search :data="$customers" id="customer_id" wire:model.lazy="taskable_id" placeholder="" />
                    <x-jet-input-error for="customer_id" class="mt-2" />
                </div>
            </div>
    </x-slot>

    <x-slot name="footer">
        <x-jet-secondary-button wire:click="$toggle('modalCreate')" wire:loading.attr="disabled">
            {{ __('Abbrechen') }}
        </x-jet-secondary-button>
        <x-jet-button class="ml-2" wire:click="store" wire:loading.attr="disabled">
            {{ __('Save') }}
        </x-jet-button>
    </x-slot>
</x-jet-dialog-modal>
</div>
@else
@endif
`

**Comment by presleyd** [comment]
What is "taskable_id" ? The empty box appears because the wire:model is
null. it should be bound to a string for a single select and an array for a
multi-select.

**Comment by xjavun** [comment]
Thank you for the quick reply.

The variable "taskable_id" was incorrect. I have corrected the source code. I have bound the wire:model to a string. 

However, it still does not work... Attached the corrected source code.

ModalSelect.php
```
<?php

namespace App\Http\Livewire;
use App\Models\Customer;


use Livewire\Component;

class ModalSelect extends Component
{
    public $customer_id = '';
    public $customers;

    public $modalCreate = false;

    public function createShowModal(){
        $this->reset('customer_id');
        $this->modalCreate = true;
    }

    public function mount()
    {
        $this->customers = collect();
        $query=Customer::with('company')->orderBy('lastName')->get();
        foreach($query as $customer){
            $this->customers->put($customer->id, $customer->lastName . ', ' . $customer->firstName . ' - ' . $customer->company->name);
        }
        $this->customers = $this->customers->toArray();
    }

    public function render()
    {
        return view('livewire.modal-select');
    }
}
```

modal-select.blade.php
```
<div>
<button type="button" wire:click="createShowModal" class="flex items-center px-5 py-2 mx-4 my-3 border border-gray-300 rounded-md text-gray-600 hover:bg-gray-600  hover:text-white text-sm font-medium focus:outline-none">
    <svg class="-ml-1 mr-2 h-5 w-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M11 9V5H9v4H5v2h4v4h2v-4h4V9h-4zm-1 11a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/></svg>
    Update
</button>

@if ($modalCreate)
<x-jet-dialog-modal wire:model="modalCreate">
    <x-slot name="title">
        {{ __('Update') }}
    </x-slot>

    <x-slot name="content">
            <div class="grid grid-cols-3 gap-4 pt-1.5">
                <div class="col-span-3">
                    <x-jet-label for="customer_id" value="{{ __('Kunde') }}" />
                    <x-select-search :data="$customers" id="customer_id" wire:model="customer_id" placeholder="" />
                    <x-jet-input-error for="customer_id" class="mt-2" />
                </div>
            </div>
    </x-slot>

    <x-slot name="footer">
        <x-jet-secondary-button wire:click="$toggle('modalCreate')" wire:loading.attr="disabled">
            {{ __('Abbrechen') }}
        </x-jet-secondary-button>
        <x-jet-button class="ml-2" wire:click="store" wire:loading.attr="disabled">
            {{ __('Save') }}
        </x-jet-button>
    </x-slot>
</x-jet-dialog-modal>
@endif
</div>
```

**Comment by xjavun** [comment]
If I place the code outside the modal, then it works both outside and inside the modal. But it is mandatory that the code is present outside the modal.
`<x-select-search :data="$customers" id="customer_id" wire:model="customer_id" placeholder="" />
`

**Comment by xjavun** [comment]
I could find out that the if-condition is responsible for the error.

It seems that it is not possible to load the select-search afterwards within a blade if condition.

So if I remove if-condition (@if ($modalCreate)) the problem is solved. However, I need the conditional...

**Comment by presleyd** [comment]
What is that conditional for? You are already binding the jet stream modal
to the modalcreate variable, that will keep it hidden but still rendered on
the page. Why do you need it to be removed from the Dom completely?

**Comment by xjavun** [comment]
The source code is only meant to serve as an example.

In practice, the user should be able to make a selection via a standard select-field. On this basis, various search-select fields are to be displayed.

For example, the user selects "Customer", then the customer select-search should be displayed. For the selection "supplier", the supplier select-search should be displayed and so on.

**Comment by presleyd** [comment]
So you don't want to use a blade @if to hide something that depends on
Javascript. At least that's my understanding. A blade @if directive removes
it completely from the DOM. You want to just hide those elements like
Alpine does with x-show. All this does is set a CSS display:none on the
element. It's still in the DOM you just can't see it. I don't think you
could put anything reactive in a blade @if statement.
